//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace API.Data.DataAccess.Repositories.EF
{
    using System;
    using System.Collections.Generic;

    [Table("OrderItems")]
    public partial class OrderItem
    {
        public int Id { get; set; }
        public int Product_Id { get; set; }
        public int Order_Id { get; set; }
        public double Count { get; set; }
        public int Price { get; set; }
    
        public virtual Order Orders { get; set; }
        public virtual Product Products { get; set; }
    }
}
