//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data.DataAccess.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string DestinationAddress { get; set; }
        public Nullable<int> AdditionalPrice { get; set; }
        public Nullable<System.DateTime> PreferableDeliveryDate { get; set; }
        public Nullable<int> State_Id { get; set; }
        public int FullPrice { get; set; }
        public string AdditionalInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual OrderStates OrderStates { get; set; }
        public virtual Users Users { get; set; }
    }
}
