//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace API.Data.DataAccess.Repositories.EF
{
    using System;
    using System.Collections.Generic;

   /// [Table("Products")]
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Type_Id { get; set; }
        public Nullable<int> CostPrice { get; set; }
        public Nullable<int> Price { get; set; }
        public int MeasUnit_Id { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<int> AvailableCount { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual MeasUnits MeasUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
