//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data.DataAccess.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int Id { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> QuantityAvalable { get; set; }
        public Nullable<bool> IsAvalable { get; set; }
        public string AdditionalInformation { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int ProductId { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
